# NumPy Foundations

In [3]:
import numpy as np

**Why we use NumPy?**
- NumPy is faster than Python lists because it stores data in contiguous memory and uses vectorized operations implemented in C.

*Problem with Python Lists*

*Python lists are:*

- Slow for math operations

- Not memory efficient

- Not optimized for numerical computing

*NumPy provides:*

- Fast arrays

- Vectorized operations

- Written in C (speed 🚀)

In [2]:
# Python Example
a = [1, 2, 3]
b = [4, 5, 6]

c = [a[i] + b[i] for i in range(len(a))]
print(c)

[5, 7, 9]


In [4]:
# NUmpy eaxmple
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


***Creating NumPy Arrays***

In [6]:
# 1-D Array (Matrix)
arr =  np.array([2,4,6,7])
print (arr)


[2 4 6 7]


In [7]:
# 2-D Array (Matrix)
matrix = np.array([7,6,5,4,3]), ([3,4,5,6,7])
print(matrix)

(array([7, 6, 5, 4, 3]), [3, 4, 5, 6, 7])


*Special Arrays*

In [8]:
# Special Arrays 
np.zeros(5)



array([0., 0., 0., 0., 0.])

In [9]:
# Ones
np.ones(5)




array([1., 1., 1., 1., 1.])

In [13]:
# Range
np.arange(0, 10, 2 )


array([0, 2, 4, 6, 8])

In [14]:
# Random
np.random.rand(5)


array([0.42680748, 0.47135779, 0.47985757, 0.40540889, 0.46146701])

In [17]:
# Identity Matrix
np.eye(7)


array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

***Practice***

*Q1 Create a NumPy array*

In [18]:
arr = np.array([7,5,4,3,7,9])
print(arr)

[7 5 4 3 7 9]


*Q2 Create a 3×3 matrix with numbers (1 to 9)*

In [19]:
matrix = np.array([1,2,3,4,5]),([2,3,4,5,6,7]), ([1,4,6,3,7])
print (matrix)

(array([1, 2, 3, 4, 5]), [2, 3, 4, 5, 6, 7], [1, 4, 6, 3, 7])


*Q3 Create an array of 5 zeros*

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])